openapi: 3.0.3
info:
  title: Advanced playlist API
  version: '2.0'
paths:
  /database/videos:
    get:
      summary: Get all videos to display
      description: Get all videos to display from internal database.
      operationId: 'getVideosFromDatabase'
      responses:
        '200':
          description: "Success: all videos within the body response."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
              examples:
                several videos:
                  value: "[{ id: 'video-AAA', title: 'Top 10 best animes' }, { id: 'video-BBB', title: 'Top 10 best movies' }]"
                no result:
                  value: "[]"
      tags:
        - database
  /providers/videos:
    get:
      summary: Get all new videos from providers
      description: Get all new videos from providers like YouTube, based on subscribed channels (saved in the database).
      operationId: 'getVideosFromProviders'
      responses:
        '200':
          description: "Success: all videos within the body response."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
              examples:
                several videos:
                  value: "[{ id: 'video-AAA', title: 'Top 10 best animes' }, { id: 'video-BBB', title: 'Top 10 best movies' }]"
                no video:
                  value: "[]"
      tags:
        - providers
  /providers/channel/{channelName}:
    get:
      summary: Search a channel with its name on all providers
      description: Search a channel with its name on all providers like YouTube.
      operationId: 'searchChannelFromProviders'
      parameters:
        - name: channelName
          description: Name of the channel to search.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Success: all channels matching the wanted name."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
              examples:
                several channels:
                  value: "[{ id: 'channel-AAA', title: 'My best channel' }, { id: 'channel-BBB', title: 'My worst channel' }]"
                no channel:
                  value: "[]"
      tags:
        - providers
tags:
  - name: database
    description: All services to manage videos saved into the internal database.
  - name: providers
    description: All services to manage videos which are hosted on an external video provider (like YouTube).
components:
  schemas:
    Video:
      type: object
      description: A video.
      properties:
        id:
          type: string
          description: Specific video ID.
        title:
          type: string
          description: Title of the video.
        url:
          type: string
          description: URL of the video.
        origin:
          type: string
          description: Origin of the video.
          enum:
          - youtube
        played:
          type: boolean
          description: Is the video has been played by the user?
          default: false
        thumbnail:
          type: string
          description: URL of the thumbnail.
        duration:
          type: integer
          format: int32
          description: Duration of the video in seconds.
        filteredStatuses:
          type: array
          description: List of filters used to hide this video.
          items:
            $ref: '#/components/schemas/FilteredStatus'
        channel:
          $ref: '#/components/schemas/Channel'
      required:
        - id
        - title
        - url
        - origin
        - played
        - duration
        - filteredStatuses
    Channel:
      type: object
      description: A video channel. A channel contains lots of videos from a user.
      properties:
        id:
          type: string
          description: Specific channel ID.
        title:
          type: string
          description: Title of the channel.
        thumbnail:
          type: string
          description: URL of the thumbnail.
        origin:
          type: object
          description: Origin of the channel.
          $ref: '#/components/schemas/Origin'
      required:
        - id
        - title
        - origin
    FilteredStatus:
      type: string
      description: Filter used to hide this video.
      enum:
        - user
        - whitelist-title
        - blacklist-title
    Origin:
      type: string
      description: Origin of the media.
      enum:
        - youtube