openapi: 3.0.3
info:
  title: Advanced playlist API
  version: '2.0'
paths:
  /database/videos:
    get:
      summary: Get all videos to display
      description: Get all videos to display from internal database.
      operationId: 'getVideosFromDatabase'
      responses:
        '200':
          description: "Success: all videos within the body response."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
              examples:
                several videos:
                  value: "[{ id: 'video-AAA', title: 'Top 10 best animes' }, { id: 'video-BBB', title: 'Top 10 best movies' }]"
                no result:
                  value: "[]"
      tags:
        - database
    post:
      summary: Save videos into the playlist
      description: Save videos into the playlist (into the internal database).
      operationId: 'saveVideos'
      requestBody:
        description: Videos to save.
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Video'
            example:
              videos to save:
                value: "[{ id: 'video-AAA', title: 'Top 10 best animes' }, { id: 'video-BBB', title: 'Top 10 best movies' }]"
      responses:
        '200':
          description: "Success: acknowledge saved videos. Only returns videos which have been saved into the database: if ID is already in the database, the video is not saved."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
              examples:
                saved videos:
                  value: "[{ id: 'video-AAA', title: 'Top 10 best animes', _databaseId: 'xxxxxxxxxx01' }, { id: 'video-BBB', title: 'Top 10 best movies', _databaseId: 'xxxxxxxxxx02' }]"
                no video saved:
                  value: "[]"
      tags:
        - database
  /database/channel:
    post:
      summary: Subscribe to a channel
      description: "Subscribe to a channel: save it into the database to fetch all videos from it. Save only if the channel does not already exist in the database."
      operationId: 'subscribeToChannel'
      requestBody:
        description: Channel to subscribe to.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'
            example:
              channel to subscribe:
                value: "{ id: 'channel-AAA', title: 'My best channel' }"
      responses:
        '200':
          description: "Success: acknowledge saved channel."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
              example:
                subscribed channel:
                  value: "{ id: 'channel-AAA', title: 'My best channel', _databaseId: 'xxxxxxxxxx' }"
        '409':
          description: "The channel already exists in the database (based on the ID)."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                subscribed channel:
                  value: "{ message: \"Channel with ID 'channel-AAA' already exists in the database.\" }"
      tags:
        - database
  /providers/videos:
    get:
      summary: Get all new videos from subscribed providers
      description: Get all new videos from providers like YouTube, based on subscribed channels (saved in the database).
      operationId: 'getVideosFromSubscribedProviders'
      responses:
        '200':
          description: "Success: all videos within the body response."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
              examples:
                several videos:
                  value: "[{ id: 'video-AAA', title: 'Top 10 best animes' }, { id: 'video-BBB', title: 'Top 10 best movies' }]"
                no video:
                  value: "[]"
      tags:
        - providers
  /providers/channel/{channelName}:
    get:
      summary: Search a channel with its name on all providers
      description: Search a channel with its name on all providers like YouTube.
      operationId: 'searchChannelFromProviders'
      parameters:
        - name: channelName
          description: Name of the channel to search.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Success: all channels matching the wanted name."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
              examples:
                several channels:
                  value: "[{ id: 'channel-AAA', title: 'My best channel' }, { id: 'channel-BBB', title: 'My worst channel' }]"
                no channel:
                  value: "[]"
      tags:
        - providers
tags:
  - name: database
    description: All services to manage videos saved into the internal database.
  - name: providers
    description: All services to manage videos which are hosted on an external video provider (like YouTube).
components:
  schemas:
    Video:
      type: object
      description: A video.
      properties:
        id:
          type: string
          description: Specific video ID.
        title:
          type: string
          description: Title of the video.
        url:
          type: string
          description: URL of the video.
        origin:
          type: string
          description: Origin of the video.
          enum:
          - youtube
        played:
          type: boolean
          description: Is the video has been played by the user?
          default: false
        thumbnail:
          type: string
          description: URL of the thumbnail.
        duration:
          type: integer
          format: int32
          description: Duration of the video in seconds.
        filteredStatuses:
          type: array
          description: List of filters used to hide this video.
          items:
            $ref: '#/components/schemas/FilteredStatus'
        channel:
          $ref: '#/components/schemas/Channel'
        _databaseId:
          type: string
          description: Technical ID for database object.
      required:
        - id
        - title
        - url
        - origin
        - played
        - duration
        - filteredStatuses
    Channel:
      type: object
      description: A video channel. A channel contains lots of videos from a user.
      properties:
        id:
          type: string
          description: Specific channel ID.
        title:
          type: string
          description: Title of the channel.
        thumbnail:
          type: string
          description: URL of the thumbnail.
        origin:
          type: object
          description: Origin of the channel.
          $ref: '#/components/schemas/Origin'
        _databaseId:
          type: string
          description: Technical ID for database object.
      required:
        - id
        - title
        - origin
    FilteredStatus:
      type: string
      description: Filter used to hide this video.
      enum:
        - user
        - whitelist-title
        - blacklist-title
    Origin:
      type: string
      description: Origin of the media.
      enum:
        - youtube
    Error:
      type: object
      description: An error occurred into the server.
      properties:
        message:
          type: string
          description: Error message.
      required:
        - message