# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ latest ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - name: Install ChromeDriver for Ubuntu
      run: npm install chromedriver@96.0.0
    - name: Export secret variables
      env:
        YT_CLIENT_API_KEY: ${{ secrets.CLIENT_API_KEY }}
        YT_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      run: |
        export CLIENT_API_KEY=$YT_CLIENT_API_KEY
        export CLIENT_ID=$YT_CLIENT_ID
    - run: npm run chrome-tests
