name: Unit tests - Server side

on:
  push:
    branches: [ '2.0' ]
  pull_request:
    branches: [ '2.0' ]
  schedule:
    - cron: '23 20 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Download OpenAPI Generator for server
      run: deno run --allow-net --allow-write --allow-read ./server/openapi-generator/download-generator.ts
    - name: Generate server
      run: mkdir -p ./server/src/main/generated/deno-oak-server/ && java -jar ./server/openapi-generator/openapi-generator-cli.jar generate -i ./server/specs/openapi.yaml -g deno-oak -o ./server/src/main/generated/deno-oak-server/
    - name: Launch tests
      run: deno test --allow-net --allow-read --allow-write ./server/src/tests/deno/